### PR TITLE
Create keytabs in /etc/trino

### PR DESCRIPTION
**Pull request by wendigo**
We could also change Kerberos principals as well (and rename presto-master to trino-master/coordinator). WDYT @findepi ?

### CODE REVIEW

**Comment by wendigo** [comment]
Failed due to `skipping https://cdn.azul.com/zulu/bin/zulu11.39.15-ca-jdk11.0.7-linux.x86_64.rpm - transfer failed`

**Comment by kokosing** [comment]
Going to restart the build.

**Review by kokosing — APPROVED** [review]

**Comment by wendigo** [comment]
@kokosing ready to merge

**Comment by kokosing** [comment]
Merged, thanks!

**Pull request merged**
