### PR TITLE
Rename Spark Iceberg image

### PR DESCRIPTION
**Pull request by alexjo2144**
Having the minor version in the image name is not helpful and has been out of date for some time.

@findepi after deploying this are you planning on removing the old image? I could try adding code to the automation to do it programmatically but it's probably easier for you to just do it manually. 

https://github.com/trinodb/docker-images/pull/123#issuecomment-1265343486

### CODE REVIEW

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
@hashhar ptal wrt release process

**Review by ebyhr — APPROVED** [review]

**Comment by hashhar** [comment]
@alexjo2144 Why would you want to remove the old image?

**Review by hashhar — APPROVED** [review]
LGTM.

Since this is entirely "new" image name release shouldn't need any manual actions.

**Comment by alexjo2144** [comment]
> @alexjo2144 Why would you want to remove the old image?

I guess I'd find it messy/confusing to have around, but If you'd rather leave it I'm fine with that

**Pull request merged**
