### PR TITLE
Add HDP3 image with KMS

### PR DESCRIPTION
**Pull request by nineinchnick**
I'm testing this manually in https://github.com/trinodb/trino/pull/18931

Needed for https://github.com/trinodb/trino/issues/1652

Based mainly on `testing/cdh5.15-hive-kerberized-kms`, with some Hive 3 patches applied, mainly permission related.

### CODE REVIEW

**Comment by nineinchnick** [comment]
Tested by building it locally:
```
make testing/hdp3.1-hive-kerberized-kms
docker tag testing/hdp3.1-hive-kerberized-kms:latest ghcr.io/trinodb/testing/hdp3.1-hive-kerberized-kms:82
```

and running tests from suite 6 in Trino:
```
./testing/bin/ptl test run \
  --jdk-tmp-download-path=$HOME/tmp/ptl-jdk \
  --trino-jdk-version=temurin21-rc \
  --config=config-default \
  --environment=singlenode-kerberos-kms-hdfs-no-impersonation \
  -- -g storage_formats
```

End result:
```
tests               | ===============================================
tests               | tempto-tests
tests               | Total tests run: 106, Failures: 0, Skips: 0
tests               | ===============================================
```

**Review by wendigo — APPROVED** [review]
Since it works, it ships 🚀

**Comment by hashhar** [comment]
let's add timeouts in ci.yml. Seems `hive3.1-hive` has tendency to get stuck (startup times out sometimes and keeps timing out) - it's been running for almost 3 hours now.

**Comment by wendigo** [comment]
@nineinchnick can you add timeouts? in a separate PR please

**Comment by wendigo** [comment]
Fetching hadoop from archive.apache.org is painfully slow :(

**Pull request merged**
